In [1]:
import pandas as pd
import numpy as np

In [2]:
trainData=pd.read_csv("C:\\Users\\jugdar_a\\Downloads\\train_E6oV3lV.csv",delimiter=",")
testData=pd.read_csv("C:\\Users\\jugdar_a\\Downloads\\test_tweets_anuFYb8.csv",delimiter=",")

In [3]:
trainData.head(3)

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty

In [4]:
trainData.label.value_counts()

0    29720
1     2242
Name: label, dtype: int64

In [5]:
testData.head(5)

id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [6]:
import re
from nltk.corpus import stopwords

In [7]:
trainData.shape

(31962, 3)

In [8]:
 stopword_set = set(stopwords.words('english'))

In [9]:
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i, '', input_txt)
        
    return input_txt   

In [10]:
trainData['tweet']=np.vectorize(remove_pattern)(trainData['tweet'], "@[\w]*")

In [11]:
testData['tweet']=np.vectorize(remove_pattern)(testData['tweet'],"@[\w]*")

# Remove punctuations

In [12]:
trainData['tweet'] = trainData['tweet'].str.replace('[^\w\s]','')
trainData['tweet'].head()

0      when a father is dysfunctional and is so sel...
1      thanks for lyft credit i cant use cause they...
2                                  bihday your majesty
3    model   i love u take with u all the time in u...
4                 factsguide society now    motivation
Name: tweet, dtype: object

In [13]:
testData['tweet'] = testData['tweet'].str.replace('[^\w\s]','')
testData['tweet'].head()

0    studiolife aislife requires passion dedication...
1      white supremacists want everyone to see the ...
2    safe ways to heal your acne    altwaystoheal h...
3    is the hp and the cursed child book up for res...
4      3rd bihday to my amazing hilarious nephew el...
Name: tweet, dtype: object

# Convert to lowercase

In [14]:
trainData['tweet'] = trainData['tweet'].apply(lambda x: " ".join(x.lower() for x in x.split()))
trainData['tweet'].head()

0    when a father is dysfunctional and is so selfi...
1    thanks for lyft credit i cant use cause they d...
2                                  bihday your majesty
3    model i love u take with u all the time in urð...
4                    factsguide society now motivation
Name: tweet, dtype: object

In [15]:
testData['tweet'] = testData['tweet'].apply(lambda x: " ".join(x.lower() for x in x.split()))
testData['tweet'].head()

0    studiolife aislife requires passion dedication...
1    white supremacists want everyone to see the ne...
2    safe ways to heal your acne altwaystoheal heal...
3    is the hp and the cursed child book up for res...
4    3rd bihday to my amazing hilarious nephew eli ...
Name: tweet, dtype: object

# Removing stopwords

In [16]:
trainData['tweet'] = trainData['tweet'].apply(lambda x: " ".join(x for x in x.split() if x not in stopword_set))
trainData['tweet'].head()

0    father dysfunctional selfish drags kids dysfun...
1    thanks lyft credit cant use cause dont offer w...
2                                       bihday majesty
3                model love u take u time urð ðððð ððð
4                        factsguide society motivation
Name: tweet, dtype: object

In [17]:
testData['tweet'] = testData['tweet'].apply(lambda x: " ".join(x for x in x.split() if x not in stopword_set))
testData['tweet'].head()

0    studiolife aislife requires passion dedication...
1    white supremacists want everyone see new â bir...
2    safe ways heal acne altwaystoheal healthy healing
3    hp cursed child book reservations already yes ...
4    3rd bihday amazing hilarious nephew eli ahmir ...
Name: tweet, dtype: object

# Removing special characters

In [18]:
import re 
#Regular expression for removing everything other than alphabets and spaces
reg = re.compile("[^a-zA-Z ]")  
spa = re.compile("[+ ]")

In [19]:
trainData['tweet'].head(5)

0    father dysfunctional selfish drags kids dysfun...
1    thanks lyft credit cant use cause dont offer w...
2                                       bihday majesty
3                model love u take u time urð ðððð ððð
4                        factsguide society motivation
Name: tweet, dtype: object

In [20]:
#Replaceing unwanted characters with null
trainData['tweet'].replace(reg,'',inplace=True)
trainData['tweet'].replace(spa,' ',inplace=True)

In [21]:
trainData['tweet'].head(5)

0    father dysfunctional selfish drags kids dysfun...
1    thanks lyft credit cant use cause dont offer w...
2                                       bihday majesty
3                        model love u take u time ur  
4                        factsguide society motivation
Name: tweet, dtype: object

In [22]:
#Replaceing unwanted characters with null
testData['tweet'].replace(reg,'',inplace=True)
testData['tweet'].replace(spa,' ',inplace=True)

In [23]:
def reduce_lengthening(text):
    pattern_ln = re.compile(r"(.)\1{2,}")
    return pattern_ln.sub(r"\1\1", text)


In [24]:
trainData['tweet']=trainData['tweet'].apply(lambda x: " ".join(reduce_lengthening(x) for x in x.split()))

In [25]:
testData['tweet']=testData['tweet'].apply(lambda x: " ".join(reduce_lengthening(x) for x in x.split()))

In [26]:
trainData['tweet'].head(5)

0    father dysfunctional selfish drags kids dysfun...
1    thanks lyft credit cant use cause dont offer w...
2                                       bihday majesty
3                          model love u take u time ur
4                        factsguide society motivation
Name: tweet, dtype: object

In [27]:
testData['tweet'].head(10)

0    studiolife aislife requires passion dedication...
1    white supremacists want everyone see new birds...
2    safe ways heal acne altwaystoheal healthy healing
3    hp cursed child book reservations already yes ...
4    rd bihday amazing hilarious nephew eli ahmir u...
5                                       choose momtips
6    something inside dies eyes ness smokeyeyes tir...
7              finishedtattooinkedinkloveit thanksalee
8      never understand dad left young deep inthefeels
9    delicious food lovelife capetown mannaepicure ...
Name: tweet, dtype: object

In [23]:
from collections import Counter

def words(text): return re.findall(r'\w+', text.lower())
WORDS = Counter(words(open('C:/Users/jugdar_a/Downloads/big.txt').read()))

def P(word, N=sum(WORDS.values())): 
    "Probability of `word`."
    return WORDS[word] / N

def correction(word): 
    "Most probable spelling correction for word."
    return max(candidates(word), key=P)

def candidates(word): 
    "Generate possible spelling corrections for word."
    return (known([word]) or known(edits1(word)) or known(edits2(word)) or [word])

def known(words): 
    "The subset of `words` that appear in the dictionary of WORDS."
    return set(w for w in words if w in WORDS)

def edits1(word):
    "All edits that are one edit away from `word`."
    letters    = 'abcdefghijklmnopqrstuvwxyz'
    splits     = [(word[:i], word[i:])    for i in range(len(word) + 1)]
    deletes    = [L + R[1:]               for L, R in splits if R]
    transposes = [L + R[1] + R[0] + R[2:] for L, R in splits if len(R)>1]
    replaces   = [L + c + R[1:]           for L, R in splits if R for c in letters]
    inserts    = [L + c + R               for L, R in splits for c in letters]
    return set(deletes + transposes + replaces + inserts)

def edits2(word): 
    "All edits that are two edits away from `word`."
    return (e2 for e1 in edits1(word) for e2 in edits1(e1))
    
"""
Exemple avec des mots au hasard 
"""
print(correction('speling'))
print(correction('fial'))
print(correction("misstkaes"))

spelling
final
mistakes


In [29]:
trainData['tweet']=trainData['tweet'].apply(lambda x: " ".join(correction(x) for x in x.split()))

In [47]:
trainData['tweet'].head(5)

0    father dysfunctional selfish drags kids dysfun...
1    thanks lyft credit cant use cause dont offer w...
2                                       bihday majesty
3                          model love u take u time ur
4                        factsguide society motivation
Name: tweet, dtype: object

In [26]:
testData['tweet']=testData['tweet'].apply(lambda x: " ".join(correction(x) for x in x.split()))

In [29]:
testData['tweet'].head(10)

0    studiolife dislike requires passion education ...
1    user white supremacists want everyone see new ...
2    safe ways heal acne altwaystoheal healthy healing
3    he cursed child book reservations already yes ...
4    rd midday amazing hilarious nephew epi their u...
5                                       choose momtips
6    something inside dies eyes ness smokeyeyes tir...
7            finishedtattooinkedinkloveit thanksaleeee
8    user user user never understand dad left young...
9    delicious food lovelife capetown mannaepicure ...
Name: tweet, dtype: object

In [29]:
trainData['token_length'] = [len(x.split(" ")) for x in trainData.tweet]
max(trainData.token_length)

23

In [28]:
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

C:\Users\jugdar_a\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [29]:
tokenizer = Tokenizer(num_words=20000) #Tokenizer is used to tokenize text
tokenizer.fit_on_texts(trainData.tweet) #Fit this to our corpus

x_train = tokenizer.texts_to_sequences(trainData.tweet) #'text to sequences converts the text to a list of indices
x_train = pad_sequences(x_train, maxlen=100) #pad_sequences makes every sequence a fixed size list by padding with 0s 

x_train.shape

(31962, 100)

In [30]:
x_test=tokenizer.texts_to_sequences(testData['tweet'])
x_test=pad_sequences(x_test,maxlen=100)

In [31]:
x_test

array([[   0,    0,    0, ..., 1196, 8725,   95],
       [   0,    0,    0, ...,  496,  379,  732],
       [   0,    0,    0, ...,   99,   28,  166],
       ...,
       [   0,    0,    0, ...,   60, 1603,  130],
       [   0,    0,    0, ...,  578,   27,  243],
       [   0,    0,    0, ..., 1425, 2899, 8809]])

In [32]:
token_index=len(tokenizer.word_index)
print(token_index)

39515


In [33]:
from keras.utils import to_categorical # This convers the labels to one-hot vectors(Dummies)

unique_labels = list(trainData.label.unique()) 
y_train = np.array([unique_labels.index(i) for i in trainData.label]) # Convert the word labels to indeces
y_train = to_categorical(y_train) # Dummify the labels
print(y_train.shape)

(31962, 2)


In [34]:
ytrain=trainData.label

In [36]:

from keras.models import Model, Input
from keras.layers import Conv1D, Embedding,MaxPooling1D,GlobalMaxPooling1D,LSTM,Dropout,Bidirectional,TimeDistributed
from keras.models import Sequential
from keras import callbacks
import keras.backend as K
from keras.utils import to_categorical
from sklearn.metrics import recall_score
from keras.layers.core import Dense, Dropout, Activation, Lambda


In [42]:
#required variables
early_stop = callbacks.EarlyStopping(monitor='val_acc', patience=2, verbose=0, mode='auto')
  
  
    #model initialization  # Call Sequential to initialize a network
model_conv = Sequential()
   
model_conv.add(Embedding(input_dim=token_index,input_length=100, output_dim=100))
model_conv.add(Dropout(0.1))
model_conv.add(Conv1D(32, 1, activation='relu'))
model_conv.add(MaxPooling1D(pool_size=4))
model_conv.add(Bidirectional(LSTM(100,return_sequences=False)))
model_conv.add(Dense(output_dim=2, activation='softmax'))
model_conv.compile(optimizer='rmsprop',  # 'Adam' is a variant of gradient descent technique
              loss='binary_crossentropy', # categorical_crossentropy for multi-class classification
              metrics=['accuracy'])# These metrics are computed and printed for evaluating
    

C:\Users\jugdar_a\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=2)`
  del sys.path[0]


In [43]:
model_conv.fit(x_train, y=y_train,batch_size=32,
          epochs=10,callbacks=[early_stop])
# Creates a HDF5 file 'my_model.h5'
model_conv.save('my_model.h5')

Epoch 1/10
31962/31962 [==============================] - 517s 16ms/step - loss: 0.1789 - acc: 0.9421
Epoch 2/10


C:\Users\jugdar_a\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\callbacks.py:535: RuntimeWarning: Early stopping conditioned on metric `val_acc` which is not available. Available metrics are: loss,acc
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning


31962/31962 [==============================] - 553s 17ms/step - loss: 0.1226 - acc: 0.9590
Epoch 3/10
31962/31962 [==============================] - 562s 18ms/step - loss: 0.1020 - acc: 0.9667
Epoch 4/10
31962/31962 [==============================] - 567s 18ms/step - loss: 0.0901 - acc: 0.9709
Epoch 5/10
31962/31962 [==============================] - 563s 18ms/step - loss: 0.0817 - acc: 0.9741
Epoch 6/10
31962/31962 [==============================] - 558s 17ms/step - loss: 0.0754 - acc: 0.9763
Epoch 7/10
31962/31962 [==============================] - 560s 18ms/step - loss: 0.0694 - acc: 0.9784
Epoch 8/10
31962/31962 [==============================] - 552s 17ms/step - loss: 0.0627 - acc: 0.9802
Epoch 9/10
31962/31962 [==============================] - 546s 17ms/step - loss: 0.0577 - acc: 0.9822
Epoch 10/10
31962/31962 [==============================] - 496s 16ms/step - loss: 0.0535 - acc: 0.9837


In [44]:
from keras.models import load_model 
model = load_model("my_model.h5")

In [45]:
prediction=model.predict(x_test)

In [46]:
prediction.shape

(17197, 2)

In [47]:
prediction

array([[8.9280248e-01, 1.0719754e-01],
       [8.2137656e-01, 1.7862342e-01],
       [9.9997401e-01, 2.5960473e-05],
       ...,
       [9.9878258e-01, 1.2173813e-03],
       [9.9995279e-01, 4.7162401e-05],
       [9.9447036e-01, 5.5296449e-03]], dtype=float32)

In [48]:
test_pred=np.argmax(prediction,axis=1) #applying for rows ..in numpy 1 is row
test_pred.shape

(17197,)

In [49]:
test_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
predictions=pd.DataFrame(test_pred)

In [51]:
predictions[0].value_counts()

0    16132
1     1065
Name: 0, dtype: int64

In [52]:
predictions.to_csv('prediction9.csv')